chef/mixlib-install

lib/mixlib/install/artifact_info.rb
lib/mixlib/install/backend/omnitruck.rb
spec/mixlib/install/backend_spec.rb

In this PR we add the ability to acquire information from omnitruck without platfom specific info. We use the brand new `/versions` endpoint. 
@schisamo @patrick-wright @thommay

Acquire version info with using platform details.

---

CONTRIBUTING.md
spec/mixlib/install/backend_spec.rb

@schisamo @patrick-wright @thommay 
Also testing if the `JSON.parse()` issues are still happening with the recent cache key change to fastly in omnitruck.

Add contributing.md that identifies the maintenance strategy and maintainers

---

lib/mixlib/install.rb
mixlib-install.gemspec
spec/mixlib/install_spec.rb
spec/spec_helper.rb
spec/support/version_manifests/opt/chef/version-manifest.json
spec/support/version_manifests/opt/chefdk/version-manifest.json

This PR adds the required helper methods to use mixlib-install in chef-ingredient.
/cc: @schisamo, @patrick-wright, @thommay, @jtimberman 
Note that there are more things to move from mixlib-install to here but they will be moved in a different PR.

Required helper methods to support chef-ingredient

---

PRODUCT_MATRIX.md
Rakefile
lib/mixlib/install/product.rb
spec/mixlib/install/product_spec.rb

This PR moves [product matrix](https://github.com/chef-cookbooks/chef-ingredient/blob/master/PRODUCT_MATRIX.md) and its helper methods from chef-cookbooks/chef-ingredient to here. A few things to keep in mind while reviewing:
1. I do not think the `package_name` column in the `PRODUCT_MATRIX.md` makes sense. I think we should add a description column for it to be more useful for the end user. But I did not do that and copied over only what we have. 
2. @jtimberman can you double check the version based logic in the matrix. I have double checked it but just in case :smile: 
/cc: @chef/engineering-services, @thommay

Move product matrix and its documentation from chef-ingredient.

---

lib/mixlib/install/product.rb
spec/mixlib/install/product_spec.rb

At this time we don't have a Push Server 2.0 - the "latest" is 1.1.6.
The logic for :latest setting the version to 1000.1000.1000 means
we'll always be > 2.0.

Remove version checks for push server 2.0

---

acceptance/Gemfile
acceptance/Gemfile.lock
acceptance/current/.acceptance/acceptance-cookbook/recipes/provision.rb
acceptance/current/.kitchen.yml
lib/mixlib/install.rb
lib/mixlib/install/generator.rb
lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1
lib/mixlib/install/generator/powershell/scripts/helpers.ps1
lib/mixlib/install/generator/powershell/scripts/install_project.ps1
lib/mixlib/install/options.rb
spec/mixlib/install/generator_spec.rb
spec/mixlib/install/options_spec.rb

first pass for supporting windows install scripts for omnitruck.
removed nightlies and prerelease switches
artifactory urls for unstable channel not yet implemented
todo:
- ~~optimize powershell install_command~~
- ~~refactor paths for Install #root and #current_version methods (and make sure they are correct)~~
- ~~validate with chef-acceptance (kitchen)~~
- ~~implement in chef-ingredient~~

Windows Support

---

acceptance/Gemfile.lock
lib/mixlib/install.rb
lib/mixlib/install/generator/bourne.rb
lib/mixlib/install/generator/bourne/scripts/fetch_metadata.sh.erb
lib/mixlib/install/generator/bourne/scripts/script_cli_parameters.sh
spec/mixlib/install_spec.rb

This PR adds the ability to render `install.sh` script to be used by omnitruck. See https://github.com/chef/omnitruck/pull/158 for the required changes on the omnibus side. 
The newly rendered script will be slightly different than the old script. Here are the main three differences:
* Function helpers are collected at the beginning of the script which relocated some sections of the script, the biggest being fetch_metadata section.
* Comments / documentation for clarity.
* Baked the http/https check for solaris into the download functions.
You can also see https://gist.github.com/sersut/c9851cde22b5e4cbd2ec which contains the diff data and an example of scripts.
/cc: @chef/engineering-services, @thommay, @lamont-granquist, @jaym

Ability to render install.sh script.

---

README.md
acceptance/unstable/.kitchen.yml
lib/mixlib/install/backend/artifactory.rb
lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/options.rb
spec/mixlib/install/backend_spec.rb
spec/mixlib/install/generator_spec.rb
spec/mixlib/install/options_spec.rb

Adds support for using `:latest` (code), or `'latest'` (kitchen.yml) when using the unstable channel against artifactory.
@jtimberman @sersut @schisamo

support latest version keyword for unstable channel

---

README.md
Rakefile
lib/mixlib/install/backend/artifactory.rb
lib/mixlib/install/backend/omnitruck.rb
lib/mixlib/install/generator/base.rb
lib/mixlib/install/options.rb
spec/mixlib/install/artifactory_spec.rb
spec/mixlib/install/options_spec.rb
spec/spec_helper.rb

… handling
1) case where required artifactory env vars are not set when using unstable channel
2) case where artifactory server can not be resolved
3) case where artifactory server returns 401 for bad credentials
4) case where user adds trailing slash to ENDPOINT
@sersut @schisamo first draft  going to refine more tomorrow and add the case where we get no results from querying artifactory or omnitruck

Improved unstable channel error handling

---

lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1.erb
lib/mixlib/install/generator/powershell/scripts/get_project_metadata_for_artifactory.ps1.erb
lib/mixlib/install/generator/powershell/scripts/install_project.ps1

There was a small copypasta typo which was just missing a forward slash from the example URL.

Fix typo in URL for PowerShell examples.

---

lib/mixlib/install/generator/bourne/scripts/helpers.sh

wget retries 20 times by default, but curl does not retry at all. This should make the two methods have similar behavior.

Add retry option to curl

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

Wind River Linux 7, used by Cisco for NX-OS and IOS-XR, has a
/etc/lsb-release file (unlike WRL5). However, the OS info we need
is actually in the os-release and cisco-release files. This change
skips reading the lsb-release file if it contains "wrlinux" so
the more appropriate OS info files can be read for this platform.
/cc @chef/engineering-services

Skipping the lsb-release section on wrlinux

---

lib/mixlib/install/product.rb
spec/mixlib/install/product_spec.rb

This will resolve `ingredient_config` not managing the manage.rb config file.
```
* ingredient_config[manage] action render
* directory[/etc/opscode-manage] action create (up to date)
* file[/etc/opscode-manage/manage.rb] action create[2016-01-21T22:37:27+00:00] WARN: File /etc/opscode-manage/manage.rb managed by file[/etc/opscode-manage/manage.rb] is really a symlink. Managing the source file instead.
[2016-01-21T22:37:27+00:00] WARN: Disable this warning by setting `manage_symlink_source true` on the resource
[2016-01-21T22:37:27+00:00] WARN: In a future Chef release, 'manage_symlink_source' will not be enabled by default
```

Fix Manage config file in product matrix

---

lib/mixlib/install/backend/artifactory.rb
lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/options.rb
spec/mixlib/install/artifactory_spec.rb

When we are running tests in CI, generally there are more than 1 parallel builds happening. When we do not use the build record we pick up the information about the latest build which most of the time is partial. Also when using `items.find()` in AQL artifactory returns a maximum of 1000 items and sometimes it doesn't include the artifacts we are looking for (We have a total of ~ 23k artifacts, way more items)
Still need to: 
Sharing this for preview and incase there are any initial comments. 
/cc: @patrick-wright, @schisamo

Use /builds endpoint to determine the latest version when using :unstable

---

spec/mixlib/install/backend_spec.rb

I think this is slightly better @jaym. Still not perfect but at least we are exercising the code path to call / parse `/versions` endpoint.
Replaces https://github.com/chef/mixlib-install/pull/55

Fix current specs by picking a version dynamically from omnitruck.

---

lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1.erb
lib/mixlib/install/generator/powershell/scripts/install_project.ps1

I've added a switch that lets people force the architecture. If the switch is not specified, it will default to `auto`, which will give 64 bit packages on the current channel if the machine supports it.

Give users a way to get 32 / 64 bit packages on Windows

---

lib/mixlib/install/generator/powershell/scripts/get_project_metadata_for_artifactory.ps1.erb

Fixes windows architecture selection when using unstable channel (artifactory)
tested locally for chef-client

add arch support for unstable channel

---

lib/mixlib/install/generator/bourne/scripts/fetch_metadata.sh.erb

This adds an extra linebreak for cosmetic reasons, as the metadata sometimes doesn't have one, and this screws up the rendering:
```
trying wget...
url	https://opscode-omnibus-packages.s3.amazonaws.com/mac_os_x/10.11/x86_64/chef-12.7.2-1.dmg
md5	b9583bb3a01fc23b31880df57b4c6111
sha256	66ffb6ab117bdb2f24cb5594c58815c7032a7a10b9e3221d34445192b15b07c5
version	12.7.2downloaded metadata file looks valid...
```

Add extra linebreak as metadata might not have one at end

---

PRODUCT_MATRIX.md
lib/mixlib/install/artifact_info.rb
lib/mixlib/install/backend/artifactory.rb
lib/mixlib/install/backend/omnitruck.rb
lib/mixlib/install/options.rb
lib/mixlib/install/product.rb
lib/mixlib/install/script_generator.rb
spec/mixlib/install/backend_spec.rb
spec/mixlib/install/generator_spec.rb
spec/mixlib/install_spec.rb

I noticed that `chef-server-ha-provisioning` was missing from the product matrix, and therefore not consumable by chef-ingredient.   This PR should fix that.
Note to reviewers:  There's two additional commits I added to this PR.  One to fix failing style checks and the second to fix a failing spec test.

Add chef-server-ha-provisioning package to the list

---

lib/mixlib/install.rb
lib/mixlib/install/generator/bourne.rb
lib/mixlib/install/generator/bourne/scripts/platform_detection.sh
lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1.erb
lib/mixlib/install/generator/powershell/scripts/get_project_metadata_for_artifactory.ps1.erb
lib/mixlib/install/generator/powershell/scripts/helpers.ps1
lib/mixlib/install/generator/powershell/scripts/platform_detection.ps1
lib/mixlib/install/options.rb
spec/mixlib/install/options_spec.rb
spec/mixlib/install_spec.rb

Adds `self.detect_platform` method to `Mixlib::Install`.
Calling the method will run the platform_detection script and parse the output in order to return a Hash of platform info.
This allows chef-ingredient to merge platform properties to be passed to the Mixlib::Install initialization.

detect platform info using api

---

lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/options.rb
spec/mixlib/install/generator_spec.rb
spec/mixlib/install/options_spec.rb

currently the powershell install command will, by default, set the architecture of the product to install based on the architecture of the installing node. Thats reasonable but the `render_command` method has no way of passing an architecture in to `Install-Product`. This adds that.
Note that it makes no sense to do this to the bourne shell script because it does not use a dynamic `architecture` variable.
One side effect of this change and where I may be making incorrect assumptions is that it removes the validation ensuring that `platform`, `platform_version`, and `architecture` are all passed together. This needs to be able to pass architecture without passing in the others and I did not see the value for changing it to remove architecture and thus removed it all together. So feel free …

allow architecture option to be passed to powershell installer

---

lib/mixlib/install/backend/bintray.rb
spec/mixlib/install/backend/bintray_spec.rb

/cc: @chef/engineering-services 
This PR goes with https://github.com/chef/omnitruck/pull/168 and exposes the `bintray_get` method to the outside world. We need this in omnitruck while polling bintray.

Expose private bintray_get method to the world.

---

lib/mixlib/install/backend.rb

This allows us to instantiate an instance of the Bintray backend after a simple `require 'mixlib/install'`.
/cc @sersut @patrick-wright

Load the Bintray backend with `Mixlib::Install::Backend`

---

lib/mixlib/install/generator/bourne/scripts/artifactory_urls.sh.erb
lib/mixlib/install/generator/bourne/scripts/fetch_metadata.sh.erb
lib/mixlib/install/generator/bourne/scripts/fetch_package.sh
lib/mixlib/install/generator/bourne/scripts/helpers.sh
lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1.erb
lib/mixlib/install/generator/powershell/scripts/get_project_metadata_for_artifactory.ps1.erb

This PR removes the usage of md5 and sha1 in `install.sh`. With the recent migration to bintray, we do not keep track of the md5 for our packages anymore. We had a conversation with @schisamo and @lamont-granquist in Slack and decided that removing sha1 and md5 is not going to lead to common breakages. 
We also wanted to add a new check using `openssl` to cover some of the historical platforms that does not have sha256 support. 
/cc: @chef/engineering-services

Remove md5 and sha1 usage from install.sh.

---

lib/mixlib/install/script_generator.rb

this uses the same version url value as we use for linux [here](https://github.com/chef/mixlib-install/blob/master/lib/mixlib/install/script_generator.rb#L110).

add a blank version value for non specific versions on windows just like linux

---

lib/mixlib/install.rb
spec/mixlib/install_spec.rb

This PR allows `#upgrade_available?` to support the case where a single platform is targeted by the `Mixlib::Install` object (e.g., when `platform`, `platform_version`, and `architecture` options are provided to the initializer). Included spec test and updated `#artifact_info` documentation to reflect that the return value may be either `Array<ArtifactInfo>` or `ArtifactInfo`.

support single-platform artifact_info in #upgrade_available?

---

lib/mixlib/install/generator/powershell/scripts/install_project.ps1
support/install_command.ps1

So you'd think that calling `start-process` with `-wait` would prevent the cmdlet returning until `msiexec` completes. In most cases it does. I have seen cases in the past where this is not the case. Oddly this works as expected on my vagrant boxes but I was investigating https://github.com/test-kitchen/kitchen-ec2/issues/241 and was able to consistently reproduce on an EC2 instance calling `start-process -wait` returns immediately and the returned `Process` instance has a blank `ExitCode`.
This forces it to block and fixed EC2. I don't know why EC2 behaves differently here but I do know I have seen this before and have had to use a similar method to work around the problem.

wait for msiexec to exit

---

lib/mixlib/install.rb
lib/mixlib/install/generator/bourne/scripts/helpers.sh
lib/mixlib/install/generator/powershell/scripts/helpers.ps1
lib/mixlib/install/version.rb
support/install_command.ps1

install_command.ps1 still referenced md5 checks.  This caused issues when using the ScriptGenerator.
There was a reference in helpers.ps1 in the generator scripts what was being bypassed, but I just removed it altogether.
@sersut @schisamo @mwrock

replace install_command.ps1 md5 with sha256

---

CHANGELOG.md
lib/mixlib/install/artifact_info.rb
lib/mixlib/install/backend/bintray.rb
spec/mixlib/install/backend/bintray_spec.rb

/cc: @patrick-wright 
Without this change when architecture is `x86_64` mixlib-install can not find any packages for `chefdk` since all `chefdk` builds are published for 32 bit only.

Use 32-bit artifacts for 64-bit on windows when we do not have native 64-bit packages available.

---

lib/mixlib/install/backend/bintray.rb
spec/mixlib/install/backend_spec.rb

/cc: @chef/engineering-services 
* Fixes https://github.com/chef/mixlib-install/issues/91
Need to update mixlib-install in omnitruck to fix https://github.com/chef/omnitruck/issues/170 once this is merged.

Return chef.bintray.com based urls for freebsd 9 artifacts.

---

CHANGELOG.md
lib/mixlib/install/generator/powershell/scripts/helpers.ps1
lib/mixlib/install/version.rb
support/install_command.ps1

Currently installing on Windows 2008 R2 because `SHA256CryptoServiceProvider` is only available in .net 3.5 and higher which is not the default runtime on Windows 2008 R2. We can use `SHA256Managed` which has a equivilent API but it is not FIPS 140-2 validated and will break if the node is running in fips mode. This should be fine since only chef-client needs FIPS compatibility.

use .net 2 compliant sha 256 class so we can install on windows 2k8r2

---

lib/mixlib/install/backend/bintray.rb
spec/mixlib/install/backend_spec.rb

/cc: @chef/engineering-services @schisamo @patrick-wright @jeremiahsnapp 
See [this](https://chefio.slack.com/archives/eng-services-support/p1460137138001949) and [this](https://chefio.slack.com/archives/eng-services-support/p1460147334002013) for an example of this failing on RHEL/CentOS 5. 
This is the list of platforms we have:
```
aix-6.1
aix-7.1
debian-6
debian-7
debian-8
el-5
el-6
el-7
freebsd-10
freebsd-9
ios_xr-6
mac_os_x-10.10
mac_os_x-10.11
mac_os_x-10.9
nexus-7
solaris2-5.10
solaris2-5.11
ubuntu-10.04
ubuntu-12.04
ubuntu-14.04
windows-2008r2
windows-2012
windows-2012r2
```
I think this change will be sufficient.

Add el-5 to the list of platforms we are returning compat download endpoints

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

Without this PR we report the `platform_version` for debian-8 like `8.0` or `8.2` where it should be `8`. This leads to failures like [this](https://travis-ci.org/chef-cookbooks/omnibus/jobs/123459983). 
Needs bumping mixlib-install in chef-ingredient.
Tests:
/cc: @chef/engineering-services

Correct debian-8 platform_detection

---

README.md
lib/mixlib/install/backend/artifactory.rb
lib/mixlib/install/backend/base.rb
lib/mixlib/install/backend/bintray.rb
lib/mixlib/install/backend/omnitruck.rb
lib/mixlib/install/options.rb
spec/fixtures/vcr/Mixlib_Install_Backend_Bintray/for_a_version_of_el_that_is_not_added_to_our_matrix/can_not_find_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_Bintray/for_a_version_of_el_that_is_not_added_to_our_matrix/when_product_version_compat_mode_is_set/finds_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_Bintray/for_a_version_of_ubuntu_that_is_not_added_to_our_matrix/can_not_find_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_Bintray/for_a_version_of_ubuntu_that_is_not_added_to_our_matrix/when_product_version_compat_mode_is_set/finds_an_artifact.yml
spec/mixlib/install/backend/bintray_spec.rb
spec/mixlib/install_spec.rb

As a user, I would like to be able to consume Chef packages on new platforms that Chef Software Inc. did not have a chance to add to its official support matrix.
As distro release new versions, it takes us some time to add them into our official support matrix which requires adding new testers and builders to our CI infrastructure. Sometimes we do this in a timely manner but even these cases we have some adventurous users who would like to try Chef on these new versions before they become publicly available.
To satisfy these scenarios this PR adds in an opt-in functionality to mixlib-install and chef-ingredient which lets users get the packages built and tested for the latest version if we do not have their specified version in our official support matrix.
As a note, we have always had …

Backwards compatibility option for platform_version.

---

support/install_command.ps1

Chef provisioning would constantly fail to install the chef client msi on our openstack windows nodes due to another msi installation already being in progress.  Added some simple retry code to detect exit code 1618 (another install in progress) and retry the installation.  Retries 10 times, although it usually works after 1 or 2.  Verified this works using latest chefdk (13.21).

Added support for retrying msi installation for exit code 1618

---

lib/mixlib/install/generator/powershell/scripts/install_project.ps1

This brings the generated PowerShell script into parity with the Bourne version which does not do any project-level validation. It also allows some additional projects to be properly installed on Windows:
* delivery-cli
* push-jobs-client
/cc @chef/engineering-services

Remove project validation in `install_project.ps1`

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

This PR brings the architecture normalization logic we have in omnitruck to platform detection scripts:
https://github.com/chef/omnitruck/blob/master/app.rb#L322-L327
/cc: @chef/engineering-services 
Testing on a 32 bit ubuntu box, notice the changed value of `:architecture`. Also tested on solaris box to make sure I am not using some fancy bash construct.
```
serdar@ip-10-194-11-63:~/mixlib-install$ bundle exec irb
irb(main):001:0> require "mixlib/install"
=> true
irb(main):002:0> Mixlib::Install.new(product_name: "chef", product_version: :latest, channel: :stable).detect_platform
=> #<Mixlib::Install:0xb989aa08 @options=#<Mixlib::Install::Options:0xb989a9f4 @options={:product_name=>"chef", :product_version=>:latest, :channel=>:stable, :platform=>"ubuntu", :platform_version=>"12.04", …
```

Normalize the architecture we detected in platform detection script.

---

lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1.erb
lib/mixlib/install/generator/powershell/scripts/helpers.ps1

Previously, since we only published i386 builds on omnitruck stable, there was logic to prevent autodetection of the platform architecture.
For the most part omnitruck metadata does the right thing if the real architecture is passed to stable.  Also, we have x86_64 builds of chef-client and deliver-cli in stable which could now be picked up by default (and i386 systems will just not see them).
Also added a bit more error handling around `new-uri` to stop the commands if there is an invalid uri, rather than showing an error and continuing to try to download.

Platform Architecture Detection on stable

---

CHANGELOG.md
PRODUCT_MATRIX.md
lib/mixlib/install/product.rb
lib/mixlib/install/version.rb
spec/mixlib/install/backend/bintray_spec.rb
spec/mixlib/install/product_spec.rb

Since we are now shipping the delivery-cli within ChefDK we need to
avoid customers to try to install it separetely.
This commit removes the delivery-cli from the Product Matrix.

Remove delivery-cli from Product Matrix

---

lib/mixlib/install/product.rb
spec/fixtures/vcr/Mixlib_Install_Backend_Artifactory_all_channels/for_manage/for_latest_version/uses_omnibus_project_name.yml
spec/fixtures/vcr/Mixlib_Install_Backend_Artifactory_all_channels/for_manage/for_version_1_21_0/uses_omnibus_project_name.yml
spec/fixtures/vcr/Mixlib_Install_Backend_Artifactory_all_channels/for_push_jobs_client/for_latest_version/uses_omnibus_project_name.yml
spec/fixtures/vcr/Mixlib_Install_Backend_Artifactory_all_channels/for_push_jobs_client/for_version_1_1_5/uses_omnibus_project_name.yml
spec/mixlib/install/backend/artifactory_all_channels_spec.rb

When `omnibus_project` was set for a product where `package_name` was being passed a block to determine the name based on version, `omnibus_project` was being set to the Proc instance because it was defaulting to the `@package_name` instance variable. This should have been calling the `package_name` method.
The resulting error was:
```
had an error: URI::InvalidURIError: bad URI(is not URI?): /api/build/#<Proc:0x00000008bff948@/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-install-1.1.0/lib/mixlib/install/product.rb:233>
```
@rhass @sersut

fix omnibus_project method

---

lib/mixlib/install/backend/artifactory.rb
lib/mixlib/install/product.rb
spec/mixlib/install/product_spec.rb

We need to provide an API for other tools (like Omnitruck) to collect a list of all project names given a product name without giving a version qualifier. For example, "manage" maps to projects "chef-manage" and "opscode-manage".
example:
```ruby
PRODUCT_MATRIX.lookup("manage").known_omnibus_projects
```
@rhass @schisamo

add known_omnibus_projects methods to Product

---

lib/mixlib/install/generator/powershell/scripts/helpers.ps1

A polyfill for Get-FileHash is provided whenever the function doesn't
exist, so the error that's emitted from Get-Command is now silenced.
Fixes https://github.com/chef/mixlib-install/issues/125

Fail silently when checking for Get-FileHash

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

Enable detection of Arista EOS platforms using the same string as ohai as discussed with @jjasghar

Recognize Arista EOS

---

lib/mixlib/install/generator/powershell/scripts/helpers.ps1
lib/mixlib/install/generator/powershell/scripts/install_project.ps1
lib/mixlib/install/script_generator.rb
support/install_command.ps1

This PR adds support for installing chef on Windows Nano. It two key code adjustments:
1. Detect if running on the `.net core` runtime and use the appropriate APIs. Most of this is just namespace changes but downloading internet content is a pretty big change.
2. If installing a file with a `.appx` extension, use the appx packaging mechanisms for detection, install and upgrade of the client.
A few things to note:
* Non-nano versions of windows should behave without any change to current logic
* There is no proxy support for nano yet. That should be addressed but I had issues getting `IWebProxy` properly implemented and am putting this to the side for now.
* The appx packager installs all packages to a common "application store" on disk. This is problematic because the path contains spaces …

Add support for Nano

---

.gitattributes
CHANGELOG.md
lib/mixlib/install/version.rb

Just for sanity sake I recloned with this branch, built a gem on windows, scp'd it to my linux box, installed it and confirmed no line endings in the files.

Release 1.2.2 with forced lf line endings

---

PRODUCT_MATRIX.md
lib/mixlib/install/product.rb
spec/mixlib/install/product_spec.rb

and omnitruck.
cc @arlimus @chris-rock @chef/engineering-services

Add InSpec to the product matrix for availability via chef-ingredient

---

.travis.yml
ci/script.sh
support/install_command.ps1

This change simply removes the additional line breaks that appear during installation on the Windows platform, reducing the gaps in the logged output.
Before:
After:
Signed-off-by: Stuart Preston <stuart@pendrica.com>

Removing extraneous line breaks from Windows install logging.

---

lib/mixlib/install/generator/bourne.rb
lib/mixlib/install/generator/powershell.rb
spec/mixlib/install/generator_spec.rb

This change will reverted once the omnitruck changes with package router have been deployed to production. This is a stop gap solution so unstable requests that depend on the install scripts (sh/ps1) will work. 
This was discovered during acceptance testing for test-kitchen while trying to install a package from unstable.
@chef/engineering-services @sersut @rhass @mwrock

add condition to allow omnitruck to accept unstable channel requests

---

lib/mixlib/install/generator/bourne.rb
lib/mixlib/install/generator/powershell.rb
spec/mixlib/install/generator_spec.rb

This removes the hack to temporarily allow unstable package requests for the install scripts to hit the omnitruck-acceptance endpoint.
We will release this just before delivering omnitruck.
@schisamo

remove omnitruck-acceptance condition

---

lib/mixlib/install/backend/base.rb
lib/mixlib/install/backend/package_router.rb
spec/mixlib/install/backend/package_router_spec.rb

@chef/engineering-services 
-from wrightp
With these changes I can GET from local omnitruck server:
`0.0.0.0:8080/stable/chef/metadata?p=el&pv=6&m=i386`
and receive:
```
sha1	f8c10dc7f1fefd4dea60473fb269a889c07d0b0a
sha256	c571b2a1a89ea205c824f23fec14f36b5c209908cd98f1b4a3417e5e68461b2e
url	https://packages.chef.io/files/stable/chef/12.14.89/el/6/chef-12.14.89-1.el6.i386.rpm
version	12.14.89
```
need confirmation that this is the desired result.

Normalize auto detect platform architectures

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

Signed-off-by: Jere Julian <jere@arista.com>
On some versions of Arista EOS `/etc/redhat-release` also exists.  Moving the check for `/etc/Eos-release` before the check for `/etc/redhat-release` ensures correct OS detection.

Reorder check for Arista EOS above RedHat/Fedora

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

`/etc/lsb-release` looks like this
```
DISTRIB_ID="Cumulus Linux"
```
The double quotes are included as part of the string and need to be escaped. 🍼 
@isharacomix

fix cumulus platform detection

---

README.md
lib/mixlib/install/backend/package_router.rb
lib/mixlib/install/options.rb
spec/mixlib/install/backend/package_router_spec.rb
spec/mixlib/install/options_spec.rb
spec/spec_helper.rb

- all requests will include a default mixlib-install header
- new option to set addition user agent headers
- vcr record new episodes option defaulted to be enabled
Custom headers will look like `mixlib-install/1.1.1 someheader`

add user agent request header support

---

CHANGELOG.md
lib/mixlib/install/product.rb
lib/mixlib/install/version.rb
spec/mixlib/install/product_spec.rb

Get/Set the installation path for any given product. Defaults to
"/opt/[product_name]".

Add `install_path` value to product details

---

lib/mixlib/install/backend/package_router.rb
lib/mixlib/install/generator/base.rb
lib/mixlib/install/generator/bourne.rb
lib/mixlib/install/generator/bourne/scripts/helpers.sh.erb
lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb
lib/mixlib/install/util.rb
spec/mixlib/install/generator_spec.rb

We are adding user-agent headers to all download requests in the install scripts.
Added specs that verify the agent header templating for `Generator::Base` class
Need to verify the following function calls:
```
$ wget -d --user-agent="User-Agent: testheader/1.2.3" https://packages.chef.io/files/stable/chef/12.15.19/ubuntu/14.04/chef_12.15.19-1_amd64.deb```
Setting --user-agent (useragent) to User-Agent: testheader/1.2.3
...
---request begin---
GET /files/stable/chef/12.15.19/ubuntu/14.04/chef_12.15.19-1_amd64.deb HTTP/1.1
User-Agent: User-Agent: testheader/1.2.3
```
```
curl -v -sL -A "User-Agent: testheader/1.2.3" https://packages.chef.io/files/stable/chef/12.15.19/ubuntu/14.04/chef_12.15.19-1_amd64.deb  > foo
...
* Server certificate:
* 	 subject: C=US; ST=California; L=San Francisco; …

[JEX-362] add user agent headers to all download requests

---

lib/mixlib/install/backend/base.rb
lib/mixlib/install/cli.rb
lib/mixlib/install/options.rb
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_version_of_windows_that_is_not_added_to_our_matrix/can_not_find_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_version_of_windows_that_is_not_added_to_our_matrix/when_product_version_compat_mode_is_set/finds_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_version_of_windows_that_is_not_added_to_our_matrix/when_product_version_compat_mode_is_set/when_a_desktop_version_is_set/finds_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_version_of_windows_that_is_not_added_to_our_matrix/when_product_version_compat_mode_is_set/when_version_ends_with_r2/finds_an_artifact.yml
spec/functional/mixlib/install/cli_spec.rb
spec/unit/mixlib/install/backend/package_router_spec.rb

Fixes #169 
Windows artifacts now work properly when platform version compat is enabled. The option is enabled by default for the CLI. There is a backlog item to research how enabling this option by default will affect mixlib-install's API. For now, it seems to be OK with the CLI utility.
Added specs and tested windows versions: 2007 (not valid, but should still work with the code), 2008, 2008r2, 2012, 2012r2, 2016, 2016r2 (doesn't exist, but get the idea)
@schisamo @sersut

Enable platform version compatibility mode for Windows artifacts

---

lib/mixlib/install/generator/powershell/scripts/install_project.ps1

It's necessary to pass `ADDLOCAL=ChefClientFeature` for complete installation of `chef-client` along with `ChefServiceFeature` and `ChefSchTaskFeature` , otherwise several binaries don't get installed inside `C:/opscode/chef/embedded/bin` folder.

Passing ChefClientFeature in ADDLOCAL parameter

---

lib/mixlib/install/script_generator.rb
spec/unit/mixlib/install/script_generator_spec.rb
support/install_command.ps1

Now we can actually use the `-download_directory` flag for Windows
systems because before we were unable to do this.
If the flag is not provided we will default to `$env:TEMP`
We no longer delete the downloaded package so we can leverage it on next
installs.
Closes https://github.com/chef/mixlib-install/issues/174
Signed-off-by: Salim Afiune <afiune@chef.io>

COOL-629 Honor -download_directory flag in ScriptGenerator

---

lib/mixlib/install/script_generator.rb
spec/unit/mixlib/install/script_generator_spec.rb

`ScriptGenerator` was written at a time when we only built a single package for both 32 and 64-bit Windows and as a result it had an Omnitruck url to fetch package metadata where the platform architecture was hardcoded to 64-bit. This would cause consumers (such as `test-kitchen`) of `ScriptGenerator`'s generated install script on 32-bit Windows to always try to download and install a 64-bit Chef package. This commit removes the hardcoded URL but a proper fix should probably be to deprecate `Mixlib::Install::ScriptGenerator.new` in favor of only using `Mixlib::Install.new`.

Don’t hardcode Windows platform version and arch in ScriptGenerator

---

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb

In some situations the strings for various variables are UTF-8 encoded. This causes issues when ruby reads the variables and the strings contain UTF-8 escape sequences and is unable to match strings as needed.
/cc @chef/engineering-services

Force ASCII encoding for variables.

---

README.md
lib/mixlib/install/options.rb
spec/unit/mixlib/install/options_spec.rb

This PR piggy backs off of platform-options-fix.
There are 3 use cases to consider:
1 - Implementations where platform options and are not configured, and compat mode is defaulted.
2 - Implementations where platform options are set, but compat mode is defaulted.
3 - Implementations where compat mode is set to true.
Use Cases 2 and 3 will be unaffected by this change.
Use Case 1 will be affected in that where results used to return an empty array may now return compatible artifacts, which I would argue is desired behavior. However, this is a change to the existing API.

dynamically resolve platform version compat mode

---

lib/mixlib/install/backend/base.rb
lib/mixlib/install/backend/package_router.rb
lib/mixlib/install/cli.rb
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_product_that_does_not_exist_in_a_specific_channel/raises_an_exception.yml
spec/functional/mixlib/install/cli_spec.rb
spec/unit/mixlib/install/backend/package_router_spec.rb

This has been a long awaited changed which will be included in the next major bump release.
Instead of returning an empty Array when there are no results, mixlib-install will now raise an AritfactsNotFound exception. The exceptions will also provide more insight into the options that were passed.
Please review the other commits to understand why I removed/replaced other exceptions that were being (read attempted to be) raised.

Raise exception when there are no results

---

lib/mixlib/install.rb
lib/mixlib/install/generator/base.rb
lib/mixlib/install/generator/bourne.rb
lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/generator/powershell/scripts/install_project.ps1.erb
lib/mixlib/install/options.rb
spec/unit/mixlib/install/generator_spec.rb

The new `install_command_options` option takes a Hash of key/value pairs.
`#install_command`:
- for ps1 this will convert the options into command lines params for the generated install command
- for sh this will convert the options to the generated set of variables
`#install_ps1` and `#install_sh`:
This will take the options and set the `context` Hash which is passed as erb templates attributes.
This feature was added to maintain parity with test-kitchen which supports the provisioner setting `http_proxy`.  However, now we can support overriding any sh variable or ps1 install param.

Install script option overrides

---

lib/mixlib/install.rb
lib/mixlib/install/generator/base.rb
lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/generator/powershell/scripts/install_project.ps1
spec/unit/mixlib/install/generator_spec.rb

I got ahead of myself with this change. `http_proxy` does not need to be templated for the class method to return the raw install.ps1 script.

remove http_proxy from context

---

.travis.yml
acceptance/windows-server-2012r2/inspec/verify.rb
lib/mixlib/install/backend/base.rb
lib/mixlib/install/backend/package_router.rb
lib/mixlib/install/options.rb
lib/mixlib/install/util.rb
mixlib-install.gemspec
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_normalized_architectures/finds_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_normalized_architectures/solaris_sun4v_/finds_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_normalized_architectures/solaris_sun4v_/no_artifact_found_displays_original_architecture/raises_correct_error.yml
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_normalized_architectures/ubuntu_amd64_/finds_an_artifact.yml
spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_normalized_architectures/ubuntu_amd64_/no_artifact_found_displays_original_architecture/raises_correct_error.yml
spec/unit/mixlib/install/backend/package_router_spec.rb
spec/unit/mixlib/install/util_spec.rb

Related to issue #199 
Also ruby 2.4 and webmock 1.0 is currently broken. I updated webmock to latest (2.0). All is good.

Refactor and expose #normalize_architecture

---

CHANGELOG.md
lib/mixlib/install/backend/package_router.rb
lib/mixlib/install/version.rb
spec/unit/mixlib/install/backend/package_router_spec.rb

available_versions now returns a list sorted by semver rather than release date
Old Response:
```ruby
irb(main):002:0> Mixlib::Install.available_versions('chef', 'stable')
=> ["12.0.3", "12.1.2", "12.2.0-rc.1", "12.2.1", "12.3.0-rc.0", "12.3.0", "10.12.0", "10.14.0", "10.14.2", "10.14.4", "10.16.0", "10.16.2", "10.16.4", "10.16.6", "10.18.0", "10.18.2", "10.20.0", "10.22.0", "10.24.0", "10.24.2", "10.24.4", "10.26.0", "10.28.0", "10.28.2", "10.30.2", "10.30.4", "10.32.2", "10.34.0", "10.34.2", "10.34.4", "11.0.0", "11.2.0", "11.4.0", "11.4.2", "11.4.4", "11.10.0", "11.10.2", "11.10.4", "11.12.0", "11.12.2", "11.12.4", "11.12.8", "11.14.2", "11.14.6", "11.16.0", "11.16.2", "11.16.4", "11.6.0", "11.6.2", "11.8.0", "11.8.2", "10.34.6", "11.18.0", "11.18.10", "11.18.12", "11.18.6", "12.0.0", …
```

Return versions sorted by mixlib-versioning

---

lib/mixlib/install/generator/powershell/scripts/install_project.ps1
spec/unit/mixlib/install/generator_spec.rb

This adds support for `download_url_override` and `checksum` options on windows.  These are already supported for *nix.
This will also resolve https://github.com/chef-cookbooks/chef_client_updater/issues/30

Support powershell download url override

---

lib/mixlib/install.rb

...to allow execution of unsigned platform detect script
@chef/engineering-services 
looks like this was just updated in a recent windows update!
https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Execution_Policies
Verified on 2008r2+

Update platform detection shellout on windows

---

lib/mixlib/install/generator/bourne/scripts/install_package.sh

Given that CI is one of the mentioned exceptions, it would be nice if my build logs didn't have scary things.
I think that syntax should be of the ancients but I defer to a higher authority.
Copying over from https://github.com/chef/omnitruck/pull/110 since that side is dead-ish.

Silence the install warning on CI systems.

---

lib/mixlib/install/product.rb

`delete_if` will modify the in-memory product_map, meaning that if you call `PRODUCT_MATRIX.products_available_on_downloads_site`, `PRODUCT_MATRIX` will only include products that are on the download site.
`#reject` will simply return a new array, which is technically what I think we want.
```ruby
▶ irb
irb(main):001:0> a = [1,2,3,4,5]
=> [1, 2, 3, 4, 5]
irb(main):002:0> a.reject { |i| i.even? }
=> [1, 3, 5]
irb(main):003:0> a
=> [1, 2, 3, 4, 5]
irb(main):004:0> a.delete_if { |i| i.even? }
=> [1, 3, 5]
irb(main):005:0> a
=> [1, 3, 5]
```
Signed-off-by: Tom Duffield <tom@chef.io>

Use reject, rather than delete_if, for products_available_on_downloads_site

---

lib/mixlib/install/generator/powershell/scripts/install_project.ps1

The chef-client-updater cookbook doesn't work behind a proxy as the `http_proxy` environment variable is overwritten by the Powershell install script being passed a null value.
This simple change just adds a guard condition so that only if a value is passed to the script is it used.
This is related to #201 
This is an Obvious fix.

Only override http proxy if a value is supplied. 

---

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb

Closes #230 
you can't store objects in $env - use a global variable instead

Fix Windows architecture detection

---

lib/mixlib/install/product.rb
spec/unit/mixlib/install/product_spec.rb

When calling `PRODUCT_MATRIX.lookup` for a product that does not exist,
we'd try to call the `version` method on nil, resulting in an "undefined
method" error. Now we return nil to the caller early before trying to
manipulate it.
Signed-off-by: Adam Leff <adam@leff.co>

Return nil when looking up non-existing products

---

README.md
lib/mixlib/install.rb
lib/mixlib/install/cli.rb
spec/unit/mixlib/install_spec.rb

add #download_artifact method to Mixlib::Install API

---

.expeditor/config.yml

I changed the maintainer group since `chef/package-distribution-maintainers` doesn't exist. 
@chef/jex-team

Update expeditor config to allow gem builds

---

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb

This should allow older verisons of .NET that are on operating systems forced to negotiate TLS 1.2 to successfully download our software using mixlib-install.
Corrects https://github.com/chef/mixlib-install/issues/253

Adding TLS negotiation support for older versions of .NET

---

.travis.yml

Precise isn't an option anymore so remove that config and switch to trusty packages. Also make sure we have the latest patch releases of ruby since Travis does weird things we the version aliases.

Switch to trusty packages and test on the latest Ruby releases in Travis

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

We're already remapping this in omnitruck which is the right place to do
it. We need to build some additional logic in there so we can properly
map the new Fedora releases to RHEL 7.

Don't remap fedora in platform_detection.sh

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

Our current detection of Amazon Linux 2 is broken. We relied on parsing out /etc/system-release contents and expecting a pretty specific text string format. Amazon changed this between the RC and the final release and broke installation on Amazon Linux 2. Total bummer.
This PR removes the logic to remap Amazon to EL 6 or 7 and instead detects Amazon via /etc/os-release and looks up the exact version from that file. This means instead of having install.sh request an download file for EL 6 it will request amazon 2018.03. This lets us handle the remapping directly in omnitruck and it also gives us the ability to actually see from the server side when users are requesting installs on Amazon Linux, which would be pretty handy to know.
Furthermore moving the logic out of install.sh and into …

Move remap logic from install.sh to omnitruck

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

The elif that looks for /etc/system-release was firing for Amazon 2 and the /etc/os-release parsing was never occurring. This moves all logic to the first check and then attempts to parse the data from /etc/os-release if the file exists (2015+). Slightly harder to grok due to the funky sh string check we have no, but it should be functional on all systems w/o risking impact to other RHEL systems.

Fix Amazon 2 detection

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

VERSION is a nice version string except on the RC release of Amazon Linux 2 where it's "2.0 (2017.12)". By switching to VERSION_ID we get "2.0" or "2" everywhere and this allows us to fetch the correct release.

Switch to VERSION_ID to detect the Amazon Linux Release

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

This aligns the names we use in the install script with ohai. We're already remapping suse to sles in omnitruck. I added a remap for opensuseleap to sles in a PR there. This is a baby step towards a single list of platform names.

Rename suse platform to opensuseleap

---

support/install_command.ps1
support/install_command.sh

We've scrubbed the docs site for the term omnibus since it doesn't mean
anything out of Chef. This will help us to scrub it from every Test
Kitchen run.

Update install scripts to not mention Omnibus

---

.expeditor/config.yml
.expeditor/update_version.sh
.travis.yml
CHANGELOG.md
Gemfile
README.md
Rakefile

Syncing changes from our other projects

Cleanup testing and expeditor configs to match other Chef projects

---

lib/mixlib/install/options.rb

Add also armv7l support
it looks like it makes the testsuite pass on Ubuntu armhf builders...

Add support for armv7l

---

lib/mixlib/install/util.rb
spec/unit/mixlib/install/util_spec.rb

This caused an issue for a customer trying to install chef-client
through a proxy. Their 'install.ps1' script ended up with a line in it
like 'previous_line=fooHTTP_PROXY=bar'. Their HTTP_PROXY was not set
and chef-client could not be downloaded.
N/A

Bug when concatenating http_proxy environment variables

---

.expeditor/config.yml
.github/CODEOWNERS
.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
.github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
.github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md
.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
.github/PULL_REQUEST_TEMPLATE.md
.github/lock.yml
.travis.yml
CONTRIBUTING.md
Gemfile

This repo is part of the Chef Foundation project. This change updates notifications and codeowners.

Update github templates and cutover to the Chef Foundation team

---

lib/mixlib/install/generator/bourne/scripts/proxy_env.sh
spec/unit/mixlib/install/generator_spec.rb

Proxy_env.sh was using bash syntax to export environment variables
bootstrapping the chef-client on Solaris servers failed due to
syntax errors.
The environment variables settings don't work with /bin/sh.  I'm trying to get knife bootstraps to work with Solaris clients.

Set the proxy environment variables using bourne shell syntax

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh
spec/unit/mixlib/install_spec.rb

Grep on some solaris servers doesn't support the -q option.
Signed-off-by: markgibbons <mark.gibbons@nordstrom.com>
Old versions of grep don't support the -q option.  When trying to discover the type of server
a lowest common denominator approach is probably needed.

Use a grep command compatible with solaris 10 and older greps

---

PRODUCT_MATRIX.md
lib/mixlib/install/product.rb
spec/functional/mixlib/install/cli_spec.rb
spec/unit/mixlib/install/backend/package_router_spec.rb
spec/unit/mixlib/install/product_spec.rb

This also removed an old test that is no longer valid and updated  the friendly names of the product so the matrix is generated correctly.

Add omnibus-gcc and fix up tests

---

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb

Right now we're identifying Windows 2019 systems as being 2016. This isn't a critical issue as our 2016 and 2019 packages are actually the same thing, but it would be good to properly identify the OS we're on. At the very least this gets us better usage data for Windows releases. The unfortunate thing is that Microsoft hasn't bumped the NT major or minor versions for 2019. Instead, they just pumped the patch (build) of the release. 2016 is 14xxx and 2019 is 17xxx. The last match wins in these switch statements so if we see a 17xxx build then identify it as 2019. 18000 is Windows 10 so I don't see them releasing a 2019 build that is in the 18000 range. If they do for some reason we'll identify these as 2016, which would be fine. I think that's the overly cautious route to take unless …

Properly identify Windows 2019 in the install.ps1

---

lib/mixlib/install.rb
lib/mixlib/install/backend.rb
lib/mixlib/install/backend/base.rb
lib/mixlib/install/backend/package_router.rb
lib/mixlib/install/cli.rb
lib/mixlib/install/generator.rb
lib/mixlib/install/generator/base.rb
lib/mixlib/install/generator/bourne.rb
lib/mixlib/install/generator/powershell.rb
lib/mixlib/install/options.rb
lib/mixlib/install/product.rb
lib/mixlib/install/product_matrix.rb
lib/mixlib/install/script_generator.rb
lib/mixlib/install/util.rb

require_relative is significantly faster and should be used when available.

Substitute require for require_relative

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh
lib/mixlib/install/options.rb
lib/mixlib/install/util.rb

Ubuntu nodes map architecutre `uname -i` to aarch64 and `dpkg --print-architecture` to arm64 so we need this mapping reflect here
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
Ubuntu nodes map architecutre `uname -i` to aarch64 and `dpkg --print-architecture` to arm64 so we need this mapping reflect here
Map arm64 architecture to aarch64

Map arm64 architecture to aarch64

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

This variable is the machine readable version ID for tools like our install script. The VERSION variable often includes friendly values like this: "7.5 (Maipo)".
We're already doing this for RHEL platforms, but currently we pull in VERSION on modern opensuse platforms and others, which breaks installs via install.sh.
- alpine - https://github.com/chef/os_release/blob/master/alpine_3_8
- clearos - https://github.com/chef/os_release/blob/master/clearos_7
- cumulus - https://github.com/chef/os_release/blob/master/cumulus_3_7
- debian - https://github.com/chef/os_release/blob/master/debian_7
- elementary - https://github.com/chef/os_release/blob/master/elementary_5
- fedora - https://github.com/chef/os_release/blob/master/fedora_28
- linuxmint - …

Use the VERSION_ID variable by default in /etc/os-release

---

lib/mixlib/install.rb
lib/mixlib/install/backend/package_router.rb
lib/mixlib/install/cli.rb
lib/mixlib/install/generator/base.rb

require is quite slow in Ruby and doing requires for things you've already required is also slow. We've used this simple hack in Chef to speed up our requires. In the omnibus installs we patch how rubygems works to make this somewhat pointless, but this will help non-omnibus installs

Optimize requires for non-omnibus installs

---

lib/mixlib/install.rb
lib/mixlib/install/dist.rb
lib/mixlib/install/script_generator.rb

Signed-off-by: Tensibai Zhaoying <tensibai@iabis.net>
Mixlib-install still had a few places not variabilized for distribution
No issue done, seems falling in the obvious fix category.

Add linux path, variabilize script_generator and install

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

This updates our platform detection check on macOS to just return the
result of running `uname -m` which properly returns `x86_64` or `arm64`
depending on which type of Mac hardware the check is run on. Full output
details on chef/omnitruck#482
Signed-off-by: Seth Chisamore <schisamo@chef.io>

Ensure platform detection logic supports Apple Silicon

---

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb

Signed-off-by: gscho <greg.c.schofield@gmail.com>
Adds a try-catch block to a powershell helper so any failure to get the `win32_operatingsystem` using `Get-CimInstance` will be tried using `Get-WmiObject` immediately after. 
#347

Fall back to Get-WmiObject if Get-CimInstance fails

---

Gemfile

We don't use this and it causes failures in Ruby 2.4 tests

Remove pry-stack-explorer test dep

---

Gemfile

Pin climate control to v0.1.0 on version of ruby older than 2.5
Signed-off-by: gscho <greg.c.schofield@gmail.com>

Lock climate_control to 0.1.0 on older rubies

---

lib/mixlib/install/generator/bourne/scripts/fetch_package.sh
lib/mixlib/install/generator/powershell/scripts/install_project.ps1.erb

Fixes #325
Signed-off-by: gscho <greg.c.schofield@gmail.com>
Parse filename correctly from URLs with query parameters.
#325

Strip query parameters when determining filename

---

README.md

Some of our examples require that we specify supported platform versions. This is not a bug, simply maintenance of our documentation.
Signed-off-by: Tom Duffield <github@tomduffield.com>

Update README examples with new platform versions

---

lib/mixlib/install/options.rb
spec/functional/mixlib/install/cli_spec.rb
spec/unit/mixlib/install/options_spec.rb

There isn't a help command for this CLI so this message in its current form is pretty useless.

Provide more helpful error messages when you need to provide more details

---

lib/mixlib/install/generator/bourne/scripts/install_package.sh

Signed-off-by: rishichawda <rishichawda@users.noreply.github.com>
Removed desktop from the list of environments where installing chef without version constraints should be fine. Desktop environments should also pin chef to a specific version.
resolve #365

Update install script warning to not mention desktop

---

.expeditor/run_windows_tests.ps1
.expeditor/verify.pipeline.yml
Gemfile
spec/functional/mixlib/install/cli_spec.rb
spec/spec_helper.rb

Signed-off-by: poornima <poorndm@progress.com>

Add ruby 3.0/3.1 tests on windows

---

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb

Signed-off-by: Thomas Powell <powell@progress.com>
Installs on non-English Windows may fail to match on "64-bit" due to localized arch names, but especially non-Latin alphabet versions, e.g., Chinese 64-bit obarchitecture is returned as "64 位"
Match on "64" only for confirming 64-bit install. 32-bit should be the exceptional case at this point, anyway.
INFC-220

Match on 64 for architecture because of different languages

---

README.md
lib/mixlib/install/backend/package_router.rb
lib/mixlib/install/options.rb
lib/mixlib/install/product.rb
spec/fixtures/extra/extra_distributions.rb
spec/spec_helper.rb
spec/unit/mixlib/install/backend_spec.rb
spec/unit/mixlib/install/with_extra_products_spec.rb

Signed-off-by: Tensibai <tensibai@iabis.net>
Mixlib-install doesn't have a native way to add supported products out of editing the product_matrix.rb file.
This make things complex to address Chef and other distribution install from the same tool (namely for cinc for what I'm insterested about).
This proposal allow to specify an extra file using the Product DSL to add products to the matrix with their own omnitruck url.
https://github.com/chef/mixlib-install/issues/339

Allow to extend the supported products of mixlib-install

---

.expeditor/verify.pipeline.yml
lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb

Add support for detecting Windows Server 2022 platform
Windows Server 2022 was being detected as 2016. Also made the platform
version detection logic more robust.
Signed-off-by: Joseph Larionov <jlarionov@webmd.net>
Fixes #376

Add support for detecting Windows Server 2022 platform

---

.expeditor/verify.pipeline.yml
.rubocop.yml
lib/mixlib/install/product_matrix.rb
spec/unit/mixlib/install/product_spec.rb

Signed-off-by: Vikram Karve <vikram.karve@progress.com>
Add product definition for chef client universal package. A more accurate approach might be to introduce a virtual `universal` architecture and have the package made available alongside macos architecture specific installers for chef-client. This would need changes in multiple places though. So opted for a somewhat independent approach that defines universal package as a separate product to be made available via omnitruck.

IPACK-285 Add product definition for chef client universal package

---

lib/mixlib/install/product_matrix.rb
spec/unit/mixlib/install/product_spec.rb

Signed-off-by: Gregory Schofield <greg.c.schofield@gmail.com>
Adds the chef foundation product to the product matrix.

Add the chef-foundation product

---

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh

The case statement for platform detections seems to have a string for wildcard (*) which fails to fetch metadata for amazon linux 1 during chef install. Fixing this.
We encountered many instances running Amazon Linux 1 throwing the following output, it looks like the platform and version are not correctly updated because of the wildcard being a string in the case statement.
amazon linux ami 2018.03 x86_64
Getting information for chef stable  for amazon linux ami...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=amazon linux ami&pv=2018.03&m=x86_64
to file /tmp/install.sh.27900/metadata.txt
trying wget...
trying curl...
cat: /tmp/install.sh.27900/metadata.txt: No such file or directory
grep: /tmp/install.sh.27900/metadata.txt: No such file or directory
downloaded metadata …

fix amazon linux1 platform and version detection

---

lib/mixlib/install/generator.rb
lib/mixlib/install/generator/base.rb
lib/mixlib/install/script_generator.rb

The install.sh and install.ps1 files are moved to the new download API and maintained there. If the options has the new key, instead of building the file, download it from the new download api.

Download install sh from new download api
