lib/mixlib/install.rb, spec/mixlib/install_spec.rb
- Add a constant with valid options
- Validate the options passed
- Dynamically send options with accessors
=> Reduce cyclomatic complexity of parse_opts

lib/mixlib/install/backend/artifactory.rb, spec/mixlib/install/backend_spec.rb
@sersut @jtimberman 
I refactored this class to make it a bit more readable (specifically prev lines 47, 49, 50)
I also noticed the opscode s3 bucket is now https, so I fixed the tests.
This will be squashed to include two commits: the artifactory changes and the spec changes
=> Refactor Backend::Artifactory

lib/mixlib/install.rb, lib/mixlib/install/generator/base.rb, lib/mixlib/install/generator/bourne.rb, lib/mixlib/install/generator/powershell.rb, lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1.erb, lib/mixlib/install/generator/powershell/scripts/install_project.ps1, spec/mixlib/install_spec.rb
This PR goes with https://github.com/chef/omnitruck/pull/158 and adds the ability to render `install.ps1` in omnitruck. 
Here is the diff that is generated with mixlib-install and one taken from omnitruck. Only one function is relocated in the file.
```
--- install_original.ps1	2015-12-08 14:40:34.000000000 -0800
+++ install_mixlib.ps1	2015-12-08 14:45:29.000000000 -0800
@@ -31,6 +31,44 @@
}
}
+function Test-ProjectPackage {
+  [cmdletbinding()]
+  param ($Path, $Algorithm = 'SHA256', $Hash)
+
+  if (-not (get-command get-filehash))   {
+    function disposable($o){($o -is [IDisposable]) -and (($o | get-member | foreach-object {$_.name}) -contains 'Dispose')}
+    function use($obj, [scriptblock]$sb){try {& $sb} catch [exception]{throw $_} finally {if (disposable $obj) {$obj.Dispose()}} } …
```
=> Ability to render installer.ps1.

acceptance/Gemfile.lock, acceptance/current/.kitchen.yml, acceptance/unstable/.acceptance/acceptance-cookbook/.gitignore, acceptance/unstable/.acceptance/acceptance-cookbook/metadata.rb, acceptance/unstable/.acceptance/acceptance-cookbook/recipes/destroy.rb, acceptance/unstable/.acceptance/acceptance-cookbook/recipes/provision.rb, acceptance/unstable/.acceptance/acceptance-cookbook/recipes/verify.rb, acceptance/unstable/.kitchen.yml, lib/mixlib/install/backend/artifactory.rb, lib/mixlib/install/generator/base.rb, lib/mixlib/install/generator/bourne.rb, lib/mixlib/install/generator/bourne/scripts/artifactory_urls.sh.erb, lib/mixlib/install/generator/bourne/scripts/fetch_metadata.sh.erb, spec/mixlib/install/backend_spec.rb, spec/mixlib/install/generator_spec.rb
=> Ability to install from artifactory in install_command for bourne shell.

Rakefile, lib/mixlib/install/backend/artifactory.rb, lib/mixlib/install/options.rb
@sersut just wanted to make this change before I forget after the long break
=> remove unnecessary memoization

support/install_command.ps1
This is a PR originally submitted by @dissonanz.  It was applied to a branch based from 0.7.0 was tagged for 0.7.1.  This PR cherry-picks that commit.
=> Fix version detection in windows (cherry pick)

PRODUCT_MATRIX.md, lib/mixlib/install/product.rb, spec/mixlib/install/product_spec.rb
/cc: @sdelano, @chef/engineering-services
=> Add chef-backend to PRODUCT_MATRIX.

PRODUCT_MATRIX.md, lib/mixlib/install/product.rb, spec/mixlib/install/product_spec.rb
=> Add omnibus toolchain as a project

PRODUCT_MATRIX.md, lib/mixlib/install/product.rb, spec/mixlib/install/product_spec.rb
=> Add angry projects

lib/mixlib/install/options.rb
=> Enable angry and toolchain projects to be valid downloads

lib/mixlib/install/options.rb
=> Add delivery-cli and push-jobs-client

.travis.yml, Rakefile, spec/mixlib/install/artifactory_spec.rb, spec/mixlib/install/backend_spec.rb
=> fix unstable specs, update rake tasks, update travis

Gemfile, Rakefile, lib/mixlib/install.rb, lib/mixlib/install/artifact_info.rb, lib/mixlib/install/backend.rb, lib/mixlib/install/backend/artifactory.rb, lib/mixlib/install/backend/omnitruck.rb, lib/mixlib/install/options.rb, lib/mixlib/install/product.rb, lib/mixlib/install/script_generator.rb, spec/mixlib/install/artifactory_spec.rb, spec/mixlib/install/backend_spec.rb, spec/mixlib/install/generator_spec.rb, spec/mixlib/install/options_spec.rb, spec/mixlib/install_spec.rb
@sersut @thommay 
It's time yeah?
=> replace finstyle with chefstyle

lib/mixlib/install/options.rb
=> add chef-server as a supported product

PRODUCT_MATRIX.md, lib/mixlib/install/options.rb, lib/mixlib/install/product.rb, spec/mixlib/install/product_spec.rb
See individual commit messages for full details.
/cc @sersut @patrick-wright
=> Fix Product Keys

spec/mixlib/install/backend_spec.rb, spec/support/version_manifests/opt/chef/version-manifest.json, spec/support/version_manifests/opt/chefdk/version-manifest.json
/cc: @chef/engineering-services
=> Fix mixlib-install specs based on the recent bintray changes in omnitruck

support/install_command.ps1
=> adding stopaction to kick in the catch statement if manifest is missing

lib/mixlib/install/backend.rb, lib/mixlib/install/backend/bintray.rb, spec/fixtures/vcr/Mixlib_Install_Backend_Bintray/for_a_missing_version_of_a_product/raises_an_error.yml, spec/mixlib/install/backend/bintray_spec.rb
=> handle bintray version not found

CHANGELOG.md, lib/mixlib/install/version.rb, mixlib-install.gemspec
@chef/engineering-services @schisamo
=> Relax all gemspec dependency versions

lib/mixlib/install/script_generator.rb
/cc: @chef/engineering-services
=> Fix travis tests.

lib/mixlib/install/backend/bintray.rb, mixlib-install.gemspec, spec/mixlib/install/backend/bintray_spec.rb
=> Update to alias ubuntu ppc64el

lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1.erb, lib/mixlib/install/generator/powershell/scripts/get_project_metadata_for_artifactory.ps1.erb
/cc @chef/engineering-services
=> Remove MOAR PowerShell project validation missed in #111

lib/mixlib/install/generator/powershell/scripts/install_project.ps1
Similar to https://github.com/chef/mixlib-install/pull/110, this adds a retry mechanism for project installs on Windows when encountering a 1618 error code (another msi installation is in progress).  The previous pull request fixed this issue for installing the chef client, but I'm encountering it once again when installing the push jobs client via the push-jobs cookbook (which depends on chef-ingredient, which depends on mixlib-install).  I'm in the process of testing this out on our stack, I will report back once I've confirmed it fixes the problem.  Submitting this prior to that confirmation to get some early feedback.
=> Added support for retrying project msi installation for exit code 1618

PRODUCT_MATRIX.md, lib/mixlib/install/backend/bintray.rb, lib/mixlib/install/product.rb, spec/fixtures/vcr/Mixlib_Install_Backend_Artifactory/when_querying_automate/uses_the_omnibus_project_name.yml, spec/fixtures/vcr/Mixlib_Install_Backend_Artifactory_all_channels/for_automate/uses_product_package_name.yml, spec/fixtures/vcr/Mixlib_Install_Backend_Bintray/for_automate/uses_product_package_name.yml, spec/fixtures/vcr_full_artifactory/Mixlib_Install_Backend_Artifactory/when_querying_automate/uses_the_omnibus_project_name.yml, spec/fixtures/vcr_full_artifactory/Mixlib_Install_Backend_Artifactory_all_channels/for_automate/uses_product_package_name.yml, spec/fixtures/vcr_full_artifactory/Mixlib_Install_Backend_Artifactory_all_channels/for_manage/for_latest_version/uses_omnibus_project_name.yml, spec/fixtures/vcr_full_artifactory/Mixlib_Install_Backend_Artifactory_all_channels/for_manage/for_version_1_21_0/uses_omnibus_project_name.yml, spec/fixtures/vcr_full_artifactory/Mixlib_Install_Backend_Artifactory_all_channels/for_push_jobs_client/for_latest_version/uses_omnibus_project_name.yml, spec/fixtures/vcr_full_artifactory/Mixlib_Install_Backend_Artifactory_all_channels/for_push_jobs_client/for_version_1_1_5/uses_omnibus_project_name.yml, spec/fixtures/vcr_full_artifactory/Mixlib_Install_Backend_Bintray/for_automate/uses_product_package_name.yml, spec/mixlib/install/backend/artifactory_all_channels_spec.rb, spec/mixlib/install/backend/artifactory_spec.rb, spec/mixlib/install/backend/bintray_spec.rb, spec/mixlib/install/product_spec.rb
This fixes #123.
/cc @chef/engineering-services @poliva83
=> Add Chef Automate to the product matrix

lib/mixlib/install/generator/bourne/scripts/helpers.sh
=> Add p5p to helpers

lib/mixlib/install/backend/bintray.rb, spec/mixlib/install/backend/bintray_spec.rb
=> Add new s390x mappings

CHANGELOG.md, lib/mixlib/install/version.rb
@schisamo @scotthain Open to changelog phrasing changes
=> 1.2.0 release

lib/mixlib/install/generator/powershell/scripts/install_project.ps1, support/install_command.ps1
We have noticed nano installs failing on azure nano instances as well as local images built differently from our packer template. There are issues with the ACLs of the appx deployed location that prevent chef from being able to be invoked.
I'd like to believe this is either a bug or an error on our part but documentation here is extremely scarce and I am trying to contact someone at microsoft for some more detailed guidance. If it is by design we may have to eventually move to .zip based installeds but I'm skeptical it will come to that.
In the meantime, this PR simply copies the bits from the appx directory to the omnibus root location instead of just linking to the original location.
=> actually copy the appx install instead of linking

.travis.yml, ci/script.sh
Add condition in script.sh to skip acceptance tests with PRs
=> Move travis script steps into script.sh

PRODUCT_MATRIX.md, lib/mixlib/install/product.rb, spec/mixlib/install/product_spec.rb
=> Update matrix to include harmony test project

lib/mixlib/install/backend/base.rb, spec/mixlib/install/backend/package_router_spec.rb
=> remove x86 arch normalization

Rakefile, bin/mixlib-install, ci/script.sh, functional/cli_spec.rb, functional/spec_helper.rb, lib/mixlib/install/cli.rb, lib/mixlib/install/generator/base.rb, lib/mixlib/install/generator/bourne/scripts/fetch_metadata.sh.erb, lib/mixlib/install/generator/powershell/scripts/get_project_metadata.ps1.erb, mixlib-install.gemspec
manual test. Not going to write automated tests at this time.
@chef/engineering-services 
@tduffield
=> mixlib-install exec

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh
=> add cumulus linux and networks platform detection support

ci/before-script.sh, ci/run-acceptance-tests.sh
Fixing issue where acceptance tests try to run on forks
=> fix travis acceptance logic

.travis.yml, CHANGELOG.md, Rakefile, lib/mixlib/install.rb, lib/mixlib/install/version.rb
TO BE RELEASED ON 12/30/2016
I just threw some lingo together. Let me know if this should change.
@schisamo
=> Deprecate major version 1

.travis.yml, ci/before-script.sh, lib/mixlib/install/cli.rb, lib/mixlib/install/product.rb, spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_version_of_el_that_is_not_added_to_our_matrix/can_not_find_an_artifact.yml, spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_version_of_el_that_is_not_added_to_our_matrix/when_product_version_compat_mode_is_set/finds_an_artifact.yml, spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_version_of_ubuntu_that_is_not_added_to_our_matrix/can_not_find_an_artifact.yml, spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_a_version_of_ubuntu_that_is_not_added_to_our_matrix/when_product_version_compat_mode_is_set/finds_an_artifact.yml, spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/for_automate/uses_product_package_name.yml, spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/when_querying_automate/uses_the_omnibus_project_name.yml, spec/unit/mixlib/install/product_spec.rb
=> handle automate and delivery version compatibility

lib/mixlib/install/cli.rb, lib/mixlib/install/options.rb, spec/functional/mixlib/install/cli_spec.rb, spec/unit/mixlib/install/backend/package_router_spec.rb, spec/unit/mixlib/install/options_spec.rb
- force configuration of all platform options when any one is being set
- optimize CLI to use validation from Options class
- optimize error handling in Options class
- remove outdate logic in CLI class
=> Configurable platform options fix and cleanup

lib/mixlib/install/product.rb, spec/unit/mixlib/install/product_spec.rb
* `github_repo` indicates where the source code can be cloned from. Will be used with Expeditor. 
* `downloads_url` indicates where artifacts can be downloaded (other than via this utility). Will be used with Expeditor.
=> Add github_repo and downloads_product_page_url metadata to products

CHANGELOG.md, lib/mixlib/install/version.rb
=> prepare v3.2.1

.travis.yml, lib/mixlib/install/backend/package_router.rb, spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/artifact_missing_metadata/does_not_have_license_content.yml, spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/artifact_missing_metadata/does_not_have_software_dependencies.yml, spec/unit/mixlib/install/backend/package_router_spec.rb
Fixes #206 
@chef/engineering-services @TrevorBramble
=> Return nil metadata values when data is missing

.rubocop.yml, .travis.yml, Gemfile, README.md, Rakefile, mixlib-install.gemspec, spec/spec_helper.rb
plus streamlining the dependencies
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
=> ruby 1.9.3 testing

lib/mixlib/install.rb, lib/mixlib/install/artifact_info.rb
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
=> fix chefstyle offenses

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb, support/install_command.ps1
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
=> MSYS-608 Fixes hash check on FIPS enabled Windows servers

.travis.yml, acceptance/windows-server-2012r2-fips/.acceptance/acceptance-cookbook/.gitignore, acceptance/windows-server-2012r2-fips/.acceptance/acceptance-cookbook/metadata.rb, acceptance/windows-server-2012r2-fips/.acceptance/acceptance-cookbook/recipes/destroy.rb, acceptance/windows-server-2012r2-fips/.acceptance/acceptance-cookbook/recipes/provision.rb, acceptance/windows-server-2012r2-fips/.acceptance/acceptance-cookbook/recipes/verify.rb, acceptance/windows-server-2012r2-fips/inspec/verify.rb, acceptance/windows-server-2012r2-fips/terraform/application.tf, acceptance/windows-server-2012r2-fips/terraform/aws.tf, acceptance/windows-server-2012r2-fips/terraform/variables.tf
Chef-acceptance test-cases for windows server 2012r2 FIPS enabled.
=> MSYS-621: Chef-acceptance test-cases for FIPS

.travis.yml, acceptance/windows-server-2012r2-fips/.acceptance/acceptance-cookbook/recipes/provision.rb
=> fix fips acceptance test

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb, lib/mixlib/install/generator/powershell/scripts/install_project.ps1, spec/unit/mixlib/install/backend/package_router_spec.rb, support/install_command.ps1
Here is  Bench-Mark after these changes.
**Download and install Chef-client With daemon option is service**
VERBOSE: Total Minutes -> 1
VERBOSE: Total Second -> 12
**Download and install Chef-client With daemon option is service on FIPS**
VERBOSE: Total Minutes -> 1
VERBOSE: Total Second -> 19
=> [In-progress] MSYS-618 - Performance tunning of Install-Project

lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb, lib/mixlib/install/generator/powershell/scripts/install_project.ps1, support/install_command.ps1
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
=> Fix for older powershell version

CHANGELOG.md, lib/mixlib/install/version.rb
=> remove item from changelog for 3.4.0

.expeditor/config.yml, Gemfile, README.md, lib/mixlib/install/generator/bourne.rb, lib/mixlib/install/generator/bourne/scripts/proxy_env.sh, spec/functional/mixlib/install/cli_spec.rb, spec/spec_helper.rb
The proxy tests could be optimized, but it's time to get this change out to the world. I've done manual testing and added some functional proxy tests.
=> add install.sh proxy support

lib/mixlib/install/options.rb
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
=> Add support for aarch64

.expeditor/config.yml, .github/CODEOWNERS
Signed-off-by: Seth Chisamore <schisamo@chef.io>
=> Send all notifications to the Package Distribution Maintainers

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh
=> add amazon linux 2.0 platform detection support

lib/mixlib/install/options.rb, spec/unit/mixlib/install/backend/package_router_spec.rb
=> Remove windows 7, 8, and 8.1 as they are no longer supported

mixlib-install.gemspec
=> Update filespec to be more selective in its inclusivity

.expeditor/config.yml, .travis.yml, Gemfile, PRODUCT_MATRIX.md, acceptance/.suites/ubuntu_install_checksum/terraform/aws.tf, acceptance/.suites/windows-nano/terraform/aws.tf, acceptance/centos_install_checksum/terraform/aws.tf, acceptance/ubuntu_install_command/terraform/aws.tf, acceptance/ubuntu_install_command_once/terraform/aws.tf, acceptance/ubuntu_install_sh/terraform/aws.tf, acceptance/windows-server-2012r2-checksum/terraform/aws.tf, acceptance/windows-server-2012r2-fips/terraform/aws.tf, acceptance/windows-server-2012r2-once/terraform/aws.tf, acceptance/windows-server-2012r2-ps1/terraform/aws.tf, lib/mixlib/install/product.rb, spec/unit/mixlib/install/product_spec.rb
Signed-off-by: Seth Chisamore <schisamo@chef.io>
=> Updates for recent product changes

.travis.yml
Rearrange things to match our other projects as well
=> Test on Ruby head in Travis

mixlib-install.gemspec
=> Don't ship the readmes with the gem artifact

lib/mixlib/install.rb, lib/mixlib/install/artifact_info.rb, lib/mixlib/install/backend.rb, lib/mixlib/install/backend/base.rb, lib/mixlib/install/backend/package_router.rb, lib/mixlib/install/cli.rb, lib/mixlib/install/generator.rb, lib/mixlib/install/generator/base.rb, lib/mixlib/install/generator/bourne.rb, lib/mixlib/install/generator/bourne/scripts/fetch_package.sh, lib/mixlib/install/generator/bourne/scripts/helpers.sh.erb, lib/mixlib/install/generator/bourne/scripts/install_package.sh, lib/mixlib/install/generator/bourne/scripts/platform_detection.sh, lib/mixlib/install/generator/powershell.rb, lib/mixlib/install/options.rb, lib/mixlib/install/product.rb, lib/mixlib/install/script_generator.rb, lib/mixlib/install/util.rb, spec/functional/mixlib/install/cli_spec.rb, spec/unit/mixlib/install/backend_spec.rb, spec/unit/mixlib/install/generator_spec.rb, spec/unit/mixlib/install/options_spec.rb, spec/unit/mixlib/install/product_spec.rb, spec/unit/mixlib/install/script_generator_spec.rb, spec/unit/mixlib/install/util_spec.rb, spec/unit/mixlib/install_spec.rb
Fix some typos
Replace another mention of omnibus package with package
Update / fix our copyrights
Add a missing license header
=> Fix typos and update copyrights

README.md
=> Add project owner information to the readme

PRODUCT_MATRIX.md
=> Update product names to match new marketing names

spec/functional/mixlib/install/cli_spec.rb
Current license unit test fails due to Chef EULA license change.
=> Update license unit test

.expeditor/config.yml, .expeditor/verify.pipeline.yml, Gemfile, README.md
=> Add buildkite PR verification

lib/mixlib/install/cli.rb, lib/mixlib/install/options.rb
Adding ubuntu-18 aarch64(arm64)
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
=> Add support for arm64 architecture

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh
Get the branding right in the install.sh comment
=> OS X -> macOS

Gemfile, lib/mixlib/install/backend/package_router.rb, lib/mixlib/install/cli.rb, lib/mixlib/install/generator/base.rb, lib/mixlib/install/generator/bourne/scripts/helpers.sh.erb, lib/mixlib/install/generator/bourne/scripts/platform_detection.sh, lib/mixlib/install/script_generator.rb, lib/mixlib/install/util.rb, spec/unit/mixlib/install/backend/package_router_spec.rb, spec/unit/mixlib/install/generator_spec.rb, spec/unit/mixlib/install/product_spec.rb
=> Fix minor spelling mistakes

.expeditor/run_linux_tests.sh, .expeditor/verify.pipeline.yml, Gemfile, Rakefile
Use our native caching
remove the unused yard deps
and add Ruby 3.0 testing
always install chefstyle in the gemfile
Add webrick gemfile dep since it's not in ruby 3
=> Test on Ruby 3.0 & use Buildkite caching

Gemfile
Pipeline was failing for older ruby versions since newer version of contracts requires ruby >=3.0
=> pin contracts to 0.16

lib/mixlib/install/generator/bourne/scripts/fetch_package.sh
=> fetch_package.sh: fix backtick position for filename extraction

.expeditor/verify.pipeline.yml, .github/CODEOWNERS, Rakefile
Signed-off-by: poornima <poorndm@progress.com>
Test Ruby 3.0 /3.1 -  A library for interacting with Chef Software Inc's software distribution systems.
=> Test Ruby3.0/3.1- IPACK-66

lib/mixlib/install/options.rb
Signed-off-by: Vikram Karve <vikram.karve@progress.com>
We need a `universal` architecture to represent macOS universal installer. Adding here so `omnitruck` considers this a legitimate architecture in view of listing packages across architectures.
=> Add universal architecture

lib/mixlib/install/generator/bourne/scripts/platform_detection.sh, lib/mixlib/install/options.rb
- [x All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> Add Rocky Linux
